### ISSUE TITLE
meta: AAP roadmap 2023 edition

### ISSUE THREAD

**Issue by atsushieno** [atsushieno/aap-core#128]
This is a roadmap for the entire Android Audio Plugin Framework in 2023. It mostly takes over Roadmap 2022: https://github.com/atsushieno/android-audio-plugin-framework/issues/96 . It will be occasionally updated as new tasks show up.

----

- Core features
  - [x] fix aapbarebonepluginsample that still has some problem that prevent migration to implicit ports
  - [ ] port-config extension [#69](https://github.com/atsushieno/android-audio-plugin-framework/issues/69)
  - [ ] dynamic manifest [#44](https://github.com/atsushieno/android-audio-plugin-framework/issues/44)
- MidiDeviceService improvements
  - [x] default activity as settings for MidiDeviceService #120 
  - [x] Presets integration.
  - [x] strict MIDI message dispatcher implementation based on atomic ops (currently it isn't).
- Apps
  - [x] build simpler aap-juce test hosting app
  - [x] create realtime application example (can be based on samples-host-engine) [#76](https://github.com/atsushieno/android-audio-plugin-framework/issues/76)
  - [ ] get augene-ng (or other tracktion_engine apps) working
  - [x] get helio-workstation (aap-juce-helio) working
- GUI integration [#34](https://github.com/atsushieno/android-audio-plugin-framework/issues/34)
  - [x] <del>design patch protocol over MIDI2 ports</del> we don't need it. See GUI.md
  - [x] plugin in-process editor - JUCE PluginEditor integration
  - [ ] plugin out-process editor - get atsushieno/aqua working.
  - [ ] plugin out-process editor - juce_emscripten integration? (for now I don't expect the official JUCE development to go further on their own wasm support)
- Testing
  - [ ] test instrument + effect connection, within a plugin connection (graph)
  - [ ] test runner app/orchestrator that can process multiple plugins from other apps [#40](https://github.com/atsushieno/android-audio-plugin-framework/issues/77)
- Community / Publication
  - [ ] move to organization
  - [x] contribution guidelines
  - [ ] MidiDeviceService apps that can be published to Play Store.
  - [x] Some PoC-ish effect plugins and effector app: can change presets by MIDI2 program change.

Removed from roadmap 2022: active sensing (we have good-ish status check now on logcat), MIDI 2.0 support in aap-core (can wait until [Android MIDI API supports it on MidiDeviceService](https://issuetracker.google.com/issues/227690391)), MIDI 2.0 apps to aap-lv2 (LV2 itself does not support MIDI2 yet), aap-juce (can wait until JUCE AudioProcessor supports MIDI2 like AU already does)

**Comment by atsushieno** [comment]
Transition to 2024 edition.
