### ISSUE TITLE
meta: GUI support implementation (take 2.)

### ISSUE THREAD

**Issue by atsushieno** [atsushieno/aap-core#158]
It takes over #150, now with Surface Control based GUI (starting a7b2449).

Now we consider these options:

- native UI based on SurfaceControlViewHost: it requires Android 11 (50%-ish devices in the world as of writing it).
- Web UI: supports widest range of devices, implementation is a bit tricky.

while killing these options:

- System Alert Window: works with earlier API versions, but requires special permission on Settings app, kinda tricky and buggy to support as it runs without host's ownership.
- Activity based UI: switching apps would kill the DAW side. Activity embedding is supported on even narrower range of devices. (We can change our mind at any time; it's just to take `instanceId` and determine whether it controls existing instance or create new.)

Here is the updated list of tasks we need to work on:

- [x] update docs (GUI.md)
- [x] parameter changes need to be reflected on the Kotlin (compose) host controls -> #177
- [x] parameter change notifications from plugin need to be reflected on Kotlin (compose) host controls -> #177
- [x] parameter change notifications from plugin need to be reflected on Web UI -> #177
- [x] aap-juce hosting (`AudioProcessorEditor::createEditor` implementation) for surface control View (using GUI extension API). Maybe the native UI takes preference over the Web UI (depending on the device's API level).

**Comment by atsushieno** [comment]
Also there are some bugs I observed so far:

- [ ] crashes if I go back to PluginList, revisit PluginDetails, and try to open native UI again.

**Comment by atsushieno** [comment]
Most of those tasks will be handled post-0.7.7 release as (to my understanding) #153 needs to be resolved (i.e. new default plugin landing app) should take place. Current app is based on static applier that is not suitable to reflect parameter changes.

**Comment by atsushieno** [comment]
- [x] aap-juce-vital crashes when aaphostsample tries to open it (OutOfMemoryError for WTF reason) - since aap-juce-simple-host has no problem with it, it is more likely an issue in androidaudioplugin-ui-compose.

**Comment by atsushieno** [comment]
The foundation layer is done. Some plugins like Dexed has individual issues, but I could confirm that:

- updating parameters on the plugin UI is reflected at Compose PluginDetails and UAPMD
- selecting preset on UAPMD or the plugin UI on UAPMD triggers parameter updates on UAPMD
- ^ so as Compose PluginDetails.

JUCE host still might have the problem (untested) but that can be tracked as individual cases.

Therefore, I close this meta issue.
