### ISSUE TITLE
meta: AAPXS v2

### ISSUE THREAD

**Issue by atsushieno** [atsushieno/aap-core#184]
I have been working on the new `aapxs-v080` branch that will bring AAPXS "v2" API and implementation, which is going to resolve a bunch of issues.

This is a meta list of the minor issues that needs to be resolved before we merge this branch to `main` (the list is updated as the development makes progress):

- [x] native UI crashes when we try to create the UI when the plugin is at ACTIVE state.
- [x] make sure that host extensions work.
- [x] aap-ayumi GUI does not show up when it is at ACTIVE state. (Interestingly aap-lv2-mda still works)

**Comment by atsushieno** [comment]
`aapxs-v080` branch is now merged into `main`.
