### ISSUE TITLE
meta: AAP roadmap 2024 edition

### ISSUE THREAD

**Issue by atsushieno** [atsushieno/aap-core#191]
This is a roadmap for the entire AAP Project in 2024. It mostly takes over Roadmap 2023: https://github.com/atsushieno/aap-core/issues/128 . It will be occasionally updated as new tasks show up.

----

- Core features
  - [ ] port-config extension [#69](https://github.com/atsushieno/aap-core/issues/69)
  - [ ] dynamic manifest [#44](https://github.com/atsushieno/aap-core/issues/44)
- Interoperability
  - [ ] MIDI-CI integration [#190](https://github.com/atsushieno/aap-core/issues/190)
  - [ ] investigate CLAP plugin API adapter [#140](https://github.com/atsushieno/aap-core/issues/140)
- Apps
  - [ ] get some tracktion_engine apps working
  - [ ] get aap-juce-helio usable in production
- GUI integration
  - [ ] explore JUCE AudioProcessorEditor integration possibility
  - [ ] plugin Web UI - get atsushieno/aqua working.
- Testing
  - [ ] test instrument + effect connection, within a plugin connection (graph)
  - [ ] test runner app/orchestrator that can process multiple plugins from other apps [#40](https://github.com/atsushieno/aap-core/issues/77)
- Community / Publication
  - [ ] move to organization
  - [ ] Publish some plugins to Play Store.
- Customer Success
  - [ ] aap-lv2 and aap-juce plugin templates
  - [ ] troubleshooting docs

Removed from roadmap 2023: plugin out-process editor: juce_emscripten integration.
